### PR TITLE
Allow SilverStripe 3.2 an minor fixes

### PR DESCRIPTION
**Pull request by Zauberfisch**

### CODE REVIEW

**Comment by Zauberfisch** [comment]
Oh, I just realised #30 actually fixes `GridFieldImporter->setCanClearData()`. If the other PR is going to be merged, I am happy to strip this commit.

**Comment by jonom** [comment]
Any chance of a merge for this? :)

**Comment by patricknelson** [comment]
Ok bump. Now we're up to `3.3` and I'm currently using this module, attempting to upgrade as well.

**Comment by patricknelson** [comment]
Funny enough, not only did I open #30 back in Nov 2015, but also #31. Now I think I need this one to be merged as well. I wish these modules were more actively maintained :sob: Then again I'm known to be pretty slow to respond to responses to my own PR's!

**Comment by jedateach** [comment]
Anyone want to take over maintaining this module?

**Comment by jonom** [comment]
Huh github doesn't have an emoji for chirping crickets. That's a shame.

This seems like a really useful module, almost seems like functionality that should be built in to model admin but I guess it makes sense to modularise wherever you can. Just curious why you want to hand it off @jedateach, I assume it's lack of resources and you want to focus on other things, or do you not see this module having much value anymore?

@patricknelson don't suppose you have any interest on taking over this module? :pray:

**Comment by jedateach** [comment]
@jonom :laughing: I agree it's useful - I just figure someone else can give the attention it deserves. I don't work much with silverstripe at present.

**Comment by patricknelson** [comment]
Yeah, I'm super active with SilverStripe at the moment and will likely continue to be for the foreseeable future. This is interesting. @jedateach Why did you move away from SilverStripe? Looking at https://github.com/burnbright I can see a ton of other modules so, if indeed this is entirely your organization and these are modules you created, it must have been a pretty important shift for you!

My hesitation is primarily:
1. I don't use it super frequently (i.e. I really spend most of my time on one main site and don't integrate it in more than one or two places, so I don't use it often as I develop)
2. Learning the ins/outs of how this module works,
3. I'm lazy (well not really, I'm just busy and haven't even circled back on many of my existing minor PR's/fixes to SS framework & CMS :sunglasses:)

Would you end up relocating the repository to my account or would I just be added as a maintainer?

**Comment by jedateach** [comment]
I have nothing against SilverStripe, it as been a career move. The main reason being that I wanted to explore working with other technologies. I'm currently working heavily with node/js dev. I still maintain some SilverStripe sites, just not every day. So there's little incentive to keep absolutely on top of things. ...but I'm willing to find ways to keep things rolling for everyone else. It isn't an isolated issue - as you've alluded to in your hesitations. I think it affects all open source.

Actually, adding contributors sounds like a good idea. I've done this with other modules.
If I add @patricknelson, @jonom and @Zauberfisch as contributors, then we have more people to review PRs. How does that sound?

On a similar note, I've wondered if there should be a SilverStripe league, like https://thephpleague.com/. That way there could be a pool of devs that share maintaining a bunch of modules that aren't necessarily core. Time to start 'thesilverstripeleauge' org?

**Comment by jedateach** [comment]
I've merged all PRs. I've run tests, but haven't done any manual tests. I've also added you all as contributors.

**Comment by jonom** [comment]
The SilverStripe league has a nice ring to it :) thanks for the merges @jedateach

**Comment by patricknelson** [comment]
@jedateach Yeah I can agree and, trust me, after over a year of pulling my hair out (to be honest) I don't blame you _the slightest bit._ In my case what I'm doing is I'm balancing the needs of my job (working with SS, contributing here and there) with my personal desire to do the same, but concurrently, so it's not a total shift per se.

That's a good idea on the SilverStripe League concept; it's something maybe you'd want to throw out to this mailing list (if you're not already on it) since I want to think there's already a tangentially related discussion regarding the reorganization of modules. This could factor into that, since then people who are part of "SilverStripe Labs" can be "unofficial" so to speak (i.e. not employees) but still there to foster  your orphaned modules :smile: 
https://groups.google.com/forum/#!forum/silverstripe-dev

**Pull request merged**
